USE mydb

DROP TABLE IF EXISTS authTokens;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS challenges;

CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL,
	email VARCHAR(255) NOT NULL,
	passwordHash VARCHAR(255) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE KEY (username)
) ENGINE = InnoDB;

CREATE TABLE authTokens (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	userId INT UNSIGNED NOT NULL,
	authToken VARCHAR(255) NOT NULL,
	expireTime INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
) ENGINE = InnoDB;

CREATE TABLE challenges (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	displayOrder INT UNSIGNED NOT NULL DEFAULT 0,
	categoryName VARCHAR(32) NOT NULL,
	categoryOrder INT UNSIGNED NOT NULL DEFAULT 0,
	points INT UNSIGNED NOT NULL DEFAULT 1,
	body TEXT NOT NULL,
	attachmentName VARCHAR(255),
	attachmentHash VARCHAR(255),
	PRIMARY KEY (id)
) ENGINE = InnoDB;
