USE mydb

DROP TABLE IF EXISTS solvedChallenges;
DROP TABLE IF EXISTS challenges;
DROP TABLE IF EXISTS authTokens;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL,
	email VARCHAR(255) NOT NULL,
	passwordHash VARCHAR(255) NOT NULL,
	points INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	UNIQUE KEY (username)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE authTokens (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	userId INT UNSIGNED NOT NULL,
	authToken VARCHAR(255) NOT NULL,
	expireTime INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE challenges (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	categoryName VARCHAR(32) NOT NULL,
	flag VARCHAR(255) NOT NULL,
	points INT UNSIGNED NOT NULL DEFAULT 1,
	body TEXT NOT NULL,
	attachmentName VARCHAR(255),
	attachmentHash VARCHAR(255),
	PRIMARY KEY (id)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE solvedChallenges (
	challengeId INT UNSIGNED NOT NULL,
	userId INT UNSIGNED NOT NULL,
	PRIMARY KEY (challengeId, userId),
	FOREIGN KEY (challengeId)
		REFERENCES challenges(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT,
	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;
